game:
  betting:
    enabled: true
    minimum: 10
    maximum: 10000000
    #in percents
    tax-amount: 10
    bet-give-commands:
      - eco give %player% %amount%
    bet-take-commands:
      - eco take %player% %amount%
  commands:
    blocked-or-allowed-commands:
      #set to true if you want the commands below to be allowed only.
      #set to false if you want to block the commands below in the duel.
      mode: true
      commands:
        - /somecommand
    #list of commands that will be executed (from console) when duel starts. You can use %player1%
    #and %player2% placeholders here. for more info %player1% is the player who sent the duel request to %player2%.
    #%player1%, %player2%, %arena_name%
    start:
      #if inventory saving is enabled, commands in /normal will not be executed
      inventory-saving-enabled:
        - kitgive %player1% rame
        - kitgive %player2% rame
      normal:
        - someblablacommand %player1% %player2% %arena_name%
    #list of commands that will be executed (from console) when duel ends. You can use %winner%
    #and %loser% placeholders here.
    #%winner%, %loser%, %arena_name%
    end:
      #if inventory saving is enabled, commands in /normal will not be executed
      inventory-saving-enabled:
        - clear %winner%
        - clear %loser%
      normal:
        - givetokensblabla %winner% 2 %arena_name%
        - removetokensblabla %loser% 3 %arena_name%
  # you can set both ones above like end: [] or start: [] to disable them.
  #Max duel time in minutes. After this time goes both players will be teleported to the spawn.
  max_duel_time: 10
  #After the duel ends how many SECONDS should we give the
  #winner to pick up the loser's item before teleporting them to the spawn
  time_to_pick_up_items: 10
#Delay in ticks. We use this after the duel ends to reset player's shield blocking delay.
#Don't touch if you don't know what this does.
default-shield-blocking-delay: 5

#Request time out time (in seconds)
request-timeout: 300

spectator:
  commands:
    #set to true if you want the commands below to be allowed only.
    #set to false if you want to block the commands below in spectator.
    mode: true
    commands:
      - /spawn
      - /leavespectator
placeholders:
  time:
    hours: "hours"
    minutes: "minutes"
    seconds: "seconds"
#here you can toggle which modules will be enabled/disabled in the server.
#if you turn off any, it will not show up in the duels GUI, so players
#won't be able to turn on/off that restriction.
modules:
  arena-selector: true
  #Disabling this will disable restriction GUI and request will be directly sent without specifying duel restrictions.
  #Use this to disable ALL restrictions.
  GUI: true
  keep-inventory:
    enabled: false
    toggled-by-default: true
  #Inventory Saving feature. when request receiver accepts the duel, if this is enabled, both players items will be
  #taken away and stored. whenever duel ends we give them their items back. You can use this if you want to give
  #players some kits in game.commands.start
  inventory-saving:
    enabled: false
    toggled-by-default: false
  restrictions:
    bow:
      enabled: true
      toggled-by-default: true
    totem:
      enabled: true
      toggled-by-default: true
    golden-apple:
      enabled: true
      toggled-by-default: true
    enchanted-golden-apple:
      enabled: true
      toggled-by-default: true
    potion:
      enabled: true
      toggled-by-default: true
    shield:
      enabled: true
      toggled-by-default: true
    elytra:
      enabled: true
      toggled-by-default: true
    ender-pearl:
      enabled: true
      toggled-by-default: true
permissions:
  #enable/disable permissions.
  #duel.command.*
  send: false
  accept: false
  deny: false
  cancel: false
  queue: false
  ignore: false
  spectate: false