name: Duel
version: '${version}'
main: net.multylands.duels.Duels
api-version: '1.20'
authors: [ GreenedDev ]
softdepend:
  - Multiverse-Core
  - PlaceholderAPI
  - Vault
description:
  this is a duels plugin created for minecraft server Multylands. it was created due to the fact that managing duels required a lot of work. for example server helper needed to moderate 1v1 players to not use restricted PvP abilities.
website: https://www.spigotmc.org/resources/114685/
commands:
  duel:
    aliases:
      - pri
      - 1v1
    description: Simply invite player to a duel with restrictions
  duels:
    description: List of duel commands.
  dueladmin:
    aliases:
      - adminduel
    description: Various admin commands.